#!/bin/bash

# Stupid wrapper arround Opencl-intercept-layer
# All the credit goes to them

function whichlib{
  ldconfig -vNX $(echo $LD_LIBRARY_PATH | sed 's/:/ /g') 2>/dev/null |
  #/usr/lib32:
  #       libstdc++.so.6 -> libstdc++.so.6.0.26
  #        libgcc_s.so.1 -> libgcc_s.so.1
  gawk -v p=$1 'match($0, /^(\S*):/, m)           { header=m[1] }    \
                match($1, "^lib") && match($1, p) { print header "/" $1}'
}

# https://github.com/intel/opencl-intercept-layer/blob/master/docs/controls.md

# Workaround to the creation of 'CLIntercept_Dump' directory
export CLI_ReportToStderr=1
export CLI_ReportToFile=0
export CLI_DumpDir='/dev/shm'

# Maybe people have libOpenCL in a strange location...
export CLI_DllName=$(whichlib libOpenCL.so | head -n 1)

VERBOSE=false
ASM=false

while true; do
  case "$1" in
    -v | --verbose ) VERBOSE=true; shift ;;
    -a | --asm ) ASM=true; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

export CLI_DevicePerformanceTiming=1
export CLI_HostPerformanceTiming=1

if [ "$ASM" = true ] ; then
    export CLI_DumpDir="$PWD/isa_dump"
    export CLI_DumpKernelISABinaries=1
fi

if [ "$VERBOSE" = true ] ; then
    export CLI_DevicePerformanceTimelineLogging=1
    export CLI_CallLogging=1
else
    export CLI_SuppressLogging=1
fi

cliloader "$@"

if [ "$ASM" = true ] ; then
    for isabin in $CLI_DumpDir/*.isabin; do
         iga64 -d $isabin -p=9 &> "$(basename "$isabin" .isabin)".asm
    done
    rm -rf -- $PWD/isa_dump
fi
